version: "3.8"

services:
  app:
    image: guilherme2041/falae-app
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - falae-net
    environment:
      - DB_USER=${{ secrets.DB_USER }}
      - DB_NAME=${{ secrets.DB_NAME }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - DB_HOST=db
      - DB_PORT=3306
      - RAILS_ENV=development
      - SENDGRID_APIKEY=${{ secrets.SENDGRID_APIKEY }}
      - FALAE_IMAGES_PATH=/images
      - SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}

  proxy:
    depends_on:
      - app
    restart: unless-stopped
    container_name: proxy_falae
    image: guilherme2041/falae-nginx
    ports:
      - "80:80"
    networks:
      - falae-net

  db:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_NAME }}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - falae-net

networks:
  falae-net:

volumes:
  mysql-data:
