name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest 

    services:
      mysql:
        image: guilherme2041/falae-app
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports: ['3306:3306']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'

      - uses: Borales/actions-yarn@v2
        with:
          cmd: install

      - name: Install Dependencies
        run: |
          sudo apt install -yqq default-libmysqlclient-dev
          gem install bundler 

      - name: Install Gems
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup database
        env:
          DB_DATABASE: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_ENV: ${{ secrets.RAILS_ENV }}
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
        run: |
          bundle exec rails db:prepare
          bundle exec rake test

      - name: Build and test with rspec
        env:
          DB_DATABASE: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_ENV: ${{ secrets.RAILS_ENV }}
        run: |
          bundle exec rspec spec

      #- name: Create Coverage Artifact
       # uses: actions/upload-artifact@v2
       # with:
       #   name: code-coverage
       #   path: coverage/
