name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: guilherme2041/falae-app
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports: ["3306:3306"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.6'

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: ${{ secrets.RAILS_ENV }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
        run: |
          bin/rails db:setup

      - name: Run tests
        env:
          DATABASE_URL: "mysql2://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
          RAILS_ENV: ${{ secrets.RAILS_ENV }}
        run: |
          bundle exec rspec
